import { Field, FeeFields, PeriodFields } from "./VatCommon";
import { evidenceFor, idOf, decimal, minor, money } from "../utils/vat";
export function VatActionFields({ action, values, set, service, documents, errors }) {
  const field = (name, title, props = {}) => <Field key={name} name={name} title={title} value={values[name]} onChange={(v) => set(name, v)} error={errors[name]} {...props} />;
  const evidence = (name, title, purpose) => field(name, title, { options: evidenceFor(documents, service.id, purpose).map((d) => ({ value: idOf(d), label: d.documentTitle || idOf(d) })), required: true });
  let preview;
  if (action === "prepare") { try { preview = money(decimal(minor(values.outputVat) - minor(values.recoverableInputVat))); } catch { /* Incomplete inputs have no preview. */ } }
  return <div className="space-y-4">
    {action === "prepare" && <><p className="rounded-lg bg-surface-secondary p-3 text-sm">Saving replaces the reviewed totals, increments the calculation revision, clears review and client approval, resets settlement, and returns this filing to Preparing.</p><div className="grid gap-4 sm:grid-cols-2">{field("outputVat", "Reviewed output VAT (AED)", { inputMode: "decimal", required: true })}{field("recoverableInputVat", "Reviewed recoverable input VAT (AED)", { inputMode: "decimal", required: true })}</div>{preview && <p>Net VAT preview: {preview}. The saved server calculation is authoritative.</p>}{evidence("workingPaper", "Working paper", "WORKING_PAPER")}<fieldset className="space-y-2"><legend className="mb-2 text-sm font-medium">Source documents (1–100)</legend>{evidenceFor(documents, service.id, "SOURCE").map((d) => <label key={d.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={(values.sourceDocuments ?? []).includes(d.id)} onChange={(event) => set("sourceDocuments", event.target.checked ? [...(values.sourceDocuments ?? []), d.id] : values.sourceDocuments.filter((v) => v !== d.id))} />{d.documentTitle || d.id}</label>)}{errors.sourceDocuments && <p role="alert" className="text-destructive">{errors.sourceDocuments}</p>}</fieldset></>}
    {action === "record-approval" && <><p className="text-sm">Record evidence of approval obtained outside Operio. This does not send an approval request.</p>{field("approverName", "Client approver name", { maxLength: 200, required: true })}{evidence("document", "Approval evidence", "APPROVAL")}</>}
    {action === "record-submission" && <><p className="text-sm">Record a return already submitted manually through EmaraTax. Filing locks the return data and cancels pending reminders.</p>{field("reference", "Submission reference", { maxLength: 200, required: true })}{field("submittedOn", "Submission date", { type: "date", required: true })}{evidence("document", "Acknowledgment evidence", "ACKNOWLEDGMENT")}</>}
    {action === "record-tax-payment" && <><p className="text-sm">This replaces the cumulative amount paid; it is not an additional payment.</p>{field("amountPaid", "Total VAT paid to date (AED)", { inputMode: "decimal", required: true })}{field("paidOn", "Payment date", { type: "date", required: true })}{evidence("document", "Tax payment evidence", "TAX_PAYMENT")}{service.details.vat.settlement?.document && field("reason", "Reason for replacing recorded payment", { multiline: true, maxLength: 1000, required: true })}</>}
    {["revise-period", "create-next-period"].includes(action) && <><p className="text-sm">{action === "revise-period" ? "Revising the period clears calculation, settlement, review and approval." : "Enter explicit dates after this period. The new filing does not copy fees, payments or evidence."}</p><PeriodFields values={values} set={set} errors={errors} /></>}
    {["cancel", "return-for-correction", "revise-period"].includes(action) && field("reason", "Reason", { multiline: true, maxLength: 1000, required: true })}
    {action === "cancel" && <p className="text-sm">The filing and evidence are retained. Cancellation does not release this period for recreation.</p>}
    {action === "return-for-correction" && <p className="text-sm">Review and approval will be cleared. The calculation is retained.</p>}
    {action === "schedule-reminder" && <><p className="text-sm">Internal follow-up task only. No email or WhatsApp notification is sent.</p>{field("followupDate", "Actual follow-up date", { type: "date", required: true })}{field("notes", "Reminder notes (one per line)", { multiline: true })}</>}
    {action === "assign" && <p className="text-sm">Assign this filing to your signed-in active Admin account. Arbitrary reassignment needs a staff-directory API.</p>}
    {action === "fee" && <><p className="text-sm">These fields are independent of VAT settlement. Clear a field to remove its recorded value.</p><FeeFields values={values} set={set} errors={errors} /></>}
    {action === "reopen" && <p className="text-sm">Reopen the retained filing in Preparing. Review and client approval must be recorded again.</p>}
  </div>;
}
