import { Link } from "react-router-dom";
import { Panel } from "./VatCommon";
import { ACTION_LABELS } from "../constants/vat";
import { showDate, label, money } from "../utils/vat";
export function EvidenceLink({ id, documents }) {
  const doc = documents.find((d) => d.id === id);
  return doc?.documentURL && /^https?:\/\//i.test(doc.documentURL) ? <a className="text-primary underline" href={doc.documentURL} target="_blank" rel="noreferrer">{doc.documentTitle || id}</a> : <span>{doc?.documentTitle || id || "Not recorded"}{doc && !doc.documentURL ? " (link unavailable)" : ""}</span>;
}
export default function VatHistory({ service, documents }) {
  return <Panel title="Filing history"><p className="text-caption text-text-muted">VAT actions only. Uploads and generic fee edits are not a complete audited history.</p>{service.previousService && <Link className="text-primary underline" to={`/vat-filings/${service.previousService}`}>Open previous period</Link>}<ol className="space-y-4">{[...(service.details.vat.history ?? [])].reverse().map((event, index) => <li key={`${event.at}-${index}`} className="space-y-2 border-l-2 border-primary/30 pl-4 text-sm"><p className="font-semibold">{ACTION_LABELS[event.action] || label(event.action)}</p><p>{event.actor || "Unknown actor"} · {event.at ? new Date(event.at).toLocaleString() : "Time not recorded"} · Revision {event.revision}</p>{event.reason && <p>Reason: {event.reason}</p>}{event.reference && <p>Reference: {event.reference}</p>}{event.document && <p>Evidence: <EvidenceLink id={event.document} documents={documents} /></p>}{event.amount != null && <p>Amount: {money(event.amount)}</p>}{event.calculation && <div><p>Output: {money(event.calculation.outputVat)} · Recoverable input: {money(event.calculation.recoverableInputVat)} · Net: {money(event.calculation.netVat)}</p><p>Working paper: <EvidenceLink id={event.calculation.workingPaper} documents={documents} /></p>{event.calculation.sourceDocuments?.map((id) => <p key={id}>Source: <EvidenceLink id={id} documents={documents} /></p>)}</div>}{event.approval && <p>Approval: {event.approval.name} · Revision {event.approval.revision} · <EvidenceLink id={event.approval.document} documents={documents} /></p>}{["periodStart", "periodEnd", "dueDate", "scheduledFor"].filter((key) => event[key]).map((key) => <p key={key}>{({ periodStart: "Period start", periodEnd: "Period end", dueDate: "Deadline", scheduledFor: "Follow-up" })[key]}: {showDate(event[key])}</p>)}{event.assignedTo && <p>Assigned to: {event.assignedTo}</p>}{event.notes?.map((note, i) => <p key={i}>{note}</p>)}</li>)}</ol>{!service.details.vat.history?.length && <p>No workflow actions recorded.</p>}</Panel>;
}
