import { useRef, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { Button } from "@operio/ui/components/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@operio/ui/components/dialog";
import useClient from "@/features/clients/hooks/useClient";
import { useVatAdmin, useVatDetail, useVatMutation } from "../hooks/useVat";
import { ACTION_LABELS, PURPOSES } from "../constants/vat";
import { actionPayload } from "../schemas/vat";
import { allowedActions, decimal, errorInfo, idOf, inputDate, label, minor, money, showDate } from "../utils/vat";
import { ErrorNotice, Field, Panel, VatGuard } from "../components/VatCommon";
import { VatActionFields } from "../components/VatActionFields";
import VatHistory, { EvidenceLink } from "../components/VatHistory";
function initialValues(service, action) {
  const vat = service.details.vat;
  return { outputVat: vat.calculation?.outputVat ?? "", recoverableInputVat: vat.calculation?.recoverableInputVat ?? "", workingPaper: vat.calculation?.workingPaper ?? "", sourceDocuments: vat.calculation?.sourceDocuments ?? [],
    periodStart: action === "create-next-period" ? "" : inputDate(vat.periodStart), periodEnd: action === "create-next-period" ? "" : inputDate(vat.periodEnd), dueDate: action === "create-next-period" ? "" : inputDate(service.dueDate),
    amountPaid: vat.settlement?.amountPaid ?? "", packagePrice: service.packagePrice ?? "", paymentStatus: service.paymentStatus ?? "", targetCompletionDate: inputDate(service.targetCompletionDate), notes: (service.notes ?? []).join("\n") };
}
function Detail({ serviceId }) {
  const query = useVatDetail(serviceId); const admin = useVatAdmin(); const navigate = useNavigate();
  const mutation = useVatMutation(); const inFlight = useRef(false);
  const [draft, setDraft] = useState(null); const [error, setError] = useState(null); const [blocked, setBlocked] = useState(false); const [reviewed, setReviewed] = useState(false);
  const [purpose, setPurpose] = useState("SOURCE"); const [file, setFile] = useState(null); const [uploaded, setUploaded] = useState({}); const [uploadError, setUploadError] = useState(null); const [uploadUnknown, setUploadUnknown] = useState(false); const [uploadKey, setUploadKey] = useState(0); const [notice, setNotice] = useState("");
  const service = query.data?.service; const documents = query.data?.documents ?? []; const reminder = query.data?.reminder;
  const client = useClient(service?.client);
  const refresh = async () => { const result = await query.refetch(); if (!result.isError) setReviewed(true); };
  const start = (action) => { setError(null); setBlocked(false); setReviewed(false); const values = initialValues(service, action); if (action === "prepare") { values.workingPaper = uploaded.WORKING_PAPER || values.workingPaper; if (uploaded.SOURCE) values.sourceDocuments = [...new Set([...values.sourceDocuments, uploaded.SOURCE])]; } const evidencePurpose = { "record-approval": "APPROVAL", "record-submission": "ACKNOWLEDGMENT", "record-tax-payment": "TAX_PAYMENT" }[action]; if (evidencePurpose) values.document = uploaded[evidencePurpose] || ""; setDraft({ action, service, values }); };
  const set = (key, value) => setDraft((previous) => ({ ...previous, values: { ...previous.values, [key]: value } }));
  const save = async (event) => {
    event.preventDefault(); if (inFlight.current || blocked) return;
    inFlight.current = true;
    try {
      setError(null);
      const payload = actionPayload(draft.action, draft.values, draft.service, documents, idOf(admin.data));
      const result = await mutation.mutateAsync({ service: draft.service, action: draft.action, payload });
      setDraft(null); setNotice("Saved. Filing details refreshed.");
      if (result.nextService) navigate(`/vat-filings/${result.nextService.id}`);
    } catch (caught) {
      setError(caught); const info = errorInfo(caught);
      if (info.uncertain || ["VERSION_CONFLICT", "INVALID_TRANSITION", "VAT_FILED_LOCKED", "VAT_REVIEW_REQUIRED", "VAT_APPROVAL_REQUIRED", "VAT_EVIDENCE_REQUIRED"].includes(info.code)) { setBlocked(true); setReviewed(false); }
    } finally { inFlight.current = false; }
  };
  const upload = async (event) => {
    event.preventDefault(); if (inFlight.current || uploadUnknown) return; inFlight.current = true;
    try { setUploadError(null); const doc = await mutation.mutateAsync({ kind: "upload", service, purpose, file }); setUploaded((previous) => ({ ...previous, [purpose]: doc.id })); setNotice(`${doc.documentTitle || "Evidence"} uploaded. It will be preselected in the matching action.`); setFile(null); setUploadKey((value) => value + 1); }
    catch (caught) { setUploadError(caught); if (errorInfo(caught).uncertain) setUploadUnknown(true); }
    finally { inFlight.current = false; }
  };
  if (query.isPending) return <p role="status" className="p-6">Loading filing…</p>;
  if (!service || query.isError) return <div className="p-6"><ErrorNotice error={query.error || new Error("Missing filing")} reload={query.refetch} /><Link to="/vat-filings">Back to filings</Link></div>;
  const vat = service.details.vat; const company = client.data?.companies?.find((c) => idOf(c) === service.company);
  const actions = allowedActions(service, reminder);
  const errors = Object.fromEntries(errorInfo(error).details.map((d) => [String(d.field).replace(/^(body|payload)\./, ""), d.issue]));
  let balance = "Not recorded"; if (vat.calculation?.netVat != null) balance = minor(vat.calculation.netVat) <= 0n ? (minor(vat.calculation.netVat) === 0n ? "No VAT payment due" : "VAT credit") : money(decimal(minor(vat.calculation.netVat) - minor(vat.settlement?.amountPaid ?? "0")));
  return <div className="space-y-5 p-4 sm:p-6"><header className="flex flex-wrap items-center justify-between gap-4"><div><Link to="/vat-filings" className="text-primary underline">VAT filings</Link><h1 className="mt-2 text-section-heading font-bold">{company?.companyName || service.company}</h1><Link to={`/clients/${service.client}?tab=filing-vat`} className="text-sm text-primary underline">{client.data?.client?.name || service.client}</Link></div><p className="rounded-full bg-primary/10 px-5 py-3 font-semibold">{service.status === "Cancelled" ? "Cancelled" : label(vat.stage)}</p></header>{notice && <p role="status" className="rounded-lg bg-surface-secondary p-3 text-sm">{notice}</p>}
    <div className="grid gap-4 lg:grid-cols-3"><Panel title="Filing progress"><p>{service.status} · {label(vat.stage)}</p><p className="text-sm">TRN snapshot: {vat.trn}</p><p className="text-sm">{showDate(vat.periodStart)} – {showDate(vat.periodEnd)}</p><p className="text-sm">Statutory deadline: {showDate(service.dueDate)}</p><p className="break-all text-sm">Assigned to: {service.assignedTo || "Unassigned"}</p><p className="text-caption text-text-muted">Record version {service.version} · Calculation revision {vat.revision}</p></Panel><Panel title="Our service fee"><p className="text-xl font-semibold">{money(service.packagePrice)}</p><p>{service.paymentStatus || "Not recorded"}</p><p className="text-caption text-text-muted">Payment to Operio. Independent of filing and tax payment.</p></Panel><Panel title="VAT settlement"><p>{vat.settlement?.status === "CREDIT" ? "VAT credit" : vat.settlement?.status === "NOT_DUE" ? "No VAT payment due" : label(vat.settlement?.status)}</p><p>Net VAT: {money(vat.calculation?.netVat)}</p><p>Total paid: {money(vat.settlement?.amountPaid)}</p><p>Balance: {balance}</p>{vat.settlement?.paidOn && <p>Paid on: {showDate(vat.settlement.paidOn)}</p>}{vat.settlement?.document && <EvidenceLink id={vat.settlement.document} documents={documents} />}</Panel></div>
    <Panel title="Workflow actions"><div className="flex flex-wrap gap-2">{actions.map((action, index) => <Button key={action} variant={index ? "outline" : "default"} disabled={mutation.isPending || query.isFetching} onClick={() => start(action)}>{ACTION_LABELS[action]}</Button>)}</div>{!Number.isInteger(service.version) && <p role="alert">This record has no valid version. Reload before editing.</p>}<p className="text-caption text-text-muted">Returns are prepared and submitted outside Operio. Client approvals and authority payments are recorded with evidence.</p></Panel>
    <Panel title="Evidence documents"><p className="text-sm text-text-secondary">Files are permanently retained and cannot be deleted or replaced in place, including before filing. Upload a new file for a replacement. Maximum 10 MiB per file.</p><form onSubmit={upload} className="grid items-end gap-3 sm:grid-cols-3"><Field title="Evidence purpose" options={PURPOSES} value={purpose} onChange={setPurpose} disabled={mutation.isPending} /><label className="grid gap-2 text-sm">File<input key={uploadKey} type="file" required disabled={mutation.isPending} onChange={(e) => setFile(e.target.files[0] ?? null)} /></label><Button type="submit" disabled={mutation.isPending || !file || uploadUnknown}>{mutation.isPending ? "Working…" : "Upload retained evidence"}</Button></form><ErrorNotice error={uploadError} reload={async () => { const result = await query.refetch(); if (!result.isError) { setUploadUnknown(false); setNotice("Documents refreshed. Check for the uploaded file before uploading again."); } }} />{PURPOSES.map((group) => <div key={group}><h3 className="mb-2 text-sm font-semibold">{label(group)}</h3><ul className="space-y-1 text-sm">{documents.filter((d) => d.service === service.id && d.purpose === group).map((d) => <li key={d.id}><EvidenceLink id={d.id} documents={documents} />{uploaded[group] === d.id && <span className="ml-2 text-text-muted">Ready to select</span>}</li>)}</ul>{!documents.some((d) => d.service === service.id && d.purpose === group) && <p className="text-caption text-text-muted">No evidence uploaded.</p>}</div>)}</Panel>
    <div className="grid gap-4 lg:grid-cols-2"><Panel title="Preparation and review"><p>Reviewed output: {money(vat.calculation?.outputVat)}</p><p>Recoverable input: {money(vat.calculation?.recoverableInputVat)}</p>{vat.calculation?.workingPaper && <p>Working paper: <EvidenceLink id={vat.calculation.workingPaper} documents={documents} /></p>}{vat.calculation?.sourceDocuments?.map((id) => <p key={id}>Source: <EvidenceLink id={id} documents={documents} /></p>)}<p>Internal review: {vat.review ? `${vat.review.actor} · revision ${vat.review.revision}` : "Not recorded"}</p><p>Client approval: {vat.approval ? `${vat.approval.name} · revision ${vat.approval.revision}` : "Not recorded"}</p>{vat.approval && <EvidenceLink id={vat.approval.document} documents={documents} />}</Panel><Panel title="Manual submission"><p>Reference: {vat.submission?.reference || "Not recorded"}</p><p>Submitted on: {showDate(vat.submission?.submittedOn)}</p>{vat.submission && <><p>Recorded by: {vat.submission.recordedBy}</p><EvidenceLink id={vat.submission.acknowledgment} documents={documents} /></>}</Panel></div>
    <Panel title="Internal reminder and notes"><p>Internal target: {showDate(service.targetCompletionDate)}</p>{reminder ? <><p>{label(reminder.state)} · {showDate(reminder.followupDate)}</p>{reminder.notes?.map((note, index) => <p key={index}>{note}</p>)}</> : <p>No current reminder.</p>}{service.notes?.map((note, index) => <p key={index}>{note}</p>)}</Panel><VatHistory service={service} documents={documents} />
    <Dialog open={Boolean(draft)} onOpenChange={(open) => { if (!open && !mutation.isPending) setDraft(null); }}><DialogContent className="max-h-[90svh] max-w-3xl space-y-5 overflow-y-auto p-5 sm:p-6"><DialogHeader className="pr-8"><DialogTitle>{ACTION_LABELS[draft?.action]}</DialogTitle><DialogDescription>Review the details before saving. Filing version {draft?.service.version}.</DialogDescription></DialogHeader>{draft && <form onSubmit={save} className="space-y-5"><fieldset disabled={mutation.isPending} className="space-y-4"><VatActionFields action={draft.action} values={draft.values} set={set} service={draft.service} documents={documents} errors={errors} /></fieldset><ErrorNotice error={error} reload={refresh} company={service.company} />{blocked && reviewed && <div className="space-y-3 rounded-lg border p-3"><p className="text-sm">Latest: {service.status} / {label(vat.stage)}, version {service.version}; net VAT {money(vat.calculation?.netVat)}, paid {money(vat.settlement?.amountPaid)}. Close this form to inspect the full refreshed history. Your entered values are retained here.</p><Button type="button" variant="outline" disabled={!actions.includes(draft.action)} onClick={() => { setDraft((previous) => ({ ...previous, service })); setBlocked(false); setError(null); }}>I reviewed the latest record; apply my draft to version {service.version}</Button></div>}<DialogFooter><Button type="button" variant="outline" disabled={mutation.isPending} onClick={() => setDraft(null)}>Close</Button><Button type="submit" disabled={mutation.isPending || blocked || !actions.includes(draft.action)}>{mutation.isPending ? "Saving…" : draft.action === "cancel" ? "Confirm cancellation" : ACTION_LABELS[draft.action]}</Button></DialogFooter></form>}</DialogContent></Dialog>
  </div>;
}
export default function VatDetailPage() { const { serviceId } = useParams(); return <VatGuard><Detail key={serviceId} serviceId={serviceId} /></VatGuard>; }
